# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7fbc27a6f6d7796a4ba8ad3052a4837d9f84fed33e3be338f2dac0bc410890c2c87b9da22e505a27c48c31082eb03bd650e8d87d71fa5d8d59882983634b3bf

test:
  secret_key_base: 9cf87775bb72c5dc6953e56778bc08b0798a280f3470a55bb635892b03fdd0012e72c1ee9c357cf09fc82130081d90e22af6a30654cb5ca08b7190d374a62580

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
